-- ==========================================
-- RESEARCHHUB DATABASE SCHEMA
-- Oracle 11g XE Compatible
-- ==========================================

CREATE TABLE ROLE (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100) NOT NULL UNIQUE,
    FACULTY VARCHAR2(100) NOT NULL
);

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    ROLE_ID NUMBER NOT NULL,
    DEPARTMENT_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    INSTITUTION VARCHAR2(150) NOT NULL,
    REGISTRATION_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',

    CONSTRAINT FK_USER_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE(ROLE_ID),

    CONSTRAINT FK_USER_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS(DEPARTMENT_ID),

    CONSTRAINT CHK_USER_STATUS
        CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE PAPERS (
    PAPER_ID NUMBER PRIMARY KEY,
    RESEARCHER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(300) NOT NULL,
    ABSTRACT CLOB NOT NULL,
    KEYWORDS VARCHAR2(500),
    SUBMISSION_DATE DATE DEFAULT SYSDATE,
    PUBLICATION_YEAR NUMBER(4),
    STATUS VARCHAR2(30) DEFAULT 'SUBMITTED',

    CONSTRAINT FK_PAPER_RESEARCHER
        FOREIGN KEY (RESEARCHER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_PAPER_STATUS
        CHECK (
            STATUS IN (
                'SUBMITTED',
                'UNDER REVIEW',
                'ACCEPTED',
                'REJECTED',
                'PUBLISHED'
            )
        )
);

CREATE TABLE PAPER_AUTHORS (
    AUTHOR_ID NUMBER PRIMARY KEY,
    PAPER_ID NUMBER NOT NULL,
    AUTHOR_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    INSTITUTION VARCHAR2(150),

    CONSTRAINT FK_AUTHOR_PAPER
        FOREIGN KEY (PAPER_ID)
        REFERENCES PAPERS(PAPER_ID)
);

CREATE TABLE REVIEW_ASSIGNMENTS (
    ASSIGNMENT_ID NUMBER PRIMARY KEY,
    PAPER_ID NUMBER NOT NULL,
    REVIEWER_ID NUMBER NOT NULL,
    ASSIGNED_DATE DATE DEFAULT SYSDATE,
    ASSIGNMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING',

    CONSTRAINT FK_ASSIGNMENT_PAPER
        FOREIGN KEY (PAPER_ID)
        REFERENCES PAPERS(PAPER_ID),

    CONSTRAINT FK_ASSIGNMENT_REVIEWER
        FOREIGN KEY (REVIEWER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_ASSIGNMENT_STATUS
        CHECK (ASSIGNMENT_STATUS IN ('PENDING','COMPLETED'))
);

CREATE TABLE REVIEWS (
    REVIEW_ID NUMBER PRIMARY KEY,
    ASSIGNMENT_ID NUMBER NOT NULL,
    SCORE NUMBER(2),
    COMMENTS CLOB,
    REVIEW_DATE DATE DEFAULT SYSDATE,
    RECOMMENDATION VARCHAR2(30),

    CONSTRAINT FK_REVIEW_ASSIGNMENT
        FOREIGN KEY (ASSIGNMENT_ID)
        REFERENCES REVIEW_ASSIGNMENTS(ASSIGNMENT_ID),

    CONSTRAINT CHK_REVIEW_SCORE
        CHECK (SCORE BETWEEN 1 AND 10),

    CONSTRAINT CHK_RECOMMENDATION
        CHECK (
            RECOMMENDATION IN (
                'ACCEPT',
                'MINOR REVISION',
                'MAJOR REVISION',
                'REJECT'
            )
        )
);

CREATE TABLE THESES (
    THESIS_ID NUMBER PRIMARY KEY,
    RESEARCHER_ID NUMBER NOT NULL,
    DEPARTMENT_ID NUMBER NOT NULL,
    TITLE VARCHAR2(300) NOT NULL,
    ABSTRACT CLOB NOT NULL,
    SUBMISSION_DATE DATE DEFAULT SYSDATE,
    VERSION_NO NUMBER DEFAULT 1,
    STATUS VARCHAR2(30) DEFAULT 'SUBMITTED',

    CONSTRAINT FK_THESIS_RESEARCHER
        FOREIGN KEY (RESEARCHER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_THESIS_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS(DEPARTMENT_ID),

    CONSTRAINT CHK_THESIS_STATUS
        CHECK (
            STATUS IN (
                'SUBMITTED',
                'UNDER REVIEW',
                'APPROVED',
                'REJECTED'
            )
        )
);

CREATE TABLE THESIS_SUPERVISIONS (
    SUPERVISION_ID NUMBER PRIMARY KEY,
    THESIS_ID NUMBER NOT NULL,
    SUPERVISOR_ID NUMBER NOT NULL,
    SUPERVISOR_TYPE VARCHAR2(20) NOT NULL,

    CONSTRAINT FK_SUPERVISION_THESIS
        FOREIGN KEY (THESIS_ID)
        REFERENCES THESES(THESIS_ID),

    CONSTRAINT FK_SUPERVISION_SUPERVISOR
        FOREIGN KEY (SUPERVISOR_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_SUPERVISOR_TYPE
        CHECK (
            SUPERVISOR_TYPE IN ('PRIMARY','CO')
        )
);

CREATE TABLE AUDIT_LOGS (
    LOG_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ACTION_TYPE VARCHAR2(30) NOT NULL,
    TABLE_NAME VARCHAR2(50) NOT NULL,
    ACTION_DATE DATE DEFAULT SYSDATE,
    DESCRIPTION VARCHAR2(500),

    CONSTRAINT FK_AUDIT_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_ACTION_TYPE
        CHECK (
            ACTION_TYPE IN (
                'INSERT',
                'UPDATE',
                'DELETE',
                'LOGIN',
                'LOGOUT'
            )
        )
);