-- =====================================================
-- RESEARCHHUB FUNCTIONS
-- =====================================================

-- Total Papers by Researcher

CREATE OR REPLACE FUNCTION GET_TOTAL_PAPERS(
    P_RESEARCHER_ID NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM PAPERS
    WHERE RESEARCHER_ID = P_RESEARCHER_ID;

    RETURN V_TOTAL;
END;
/

-- Total Theses by Researcher

CREATE OR REPLACE FUNCTION GET_TOTAL_THESES(
    P_RESEARCHER_ID NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM THESES
    WHERE RESEARCHER_ID = P_RESEARCHER_ID;

    RETURN V_TOTAL;
END;
/

-- Average Review Score of a Paper

CREATE OR REPLACE FUNCTION GET_AVG_REVIEW_SCORE(
    P_PAPER_ID NUMBER
)
RETURN NUMBER
IS
    V_AVG NUMBER;
BEGIN
    SELECT AVG(R.SCORE)
    INTO V_AVG
    FROM REVIEWS R
    JOIN REVIEW_ASSIGNMENTS RA
        ON R.ASSIGNMENT_ID = RA.ASSIGNMENT_ID
    WHERE RA.PAPER_ID = P_PAPER_ID;

    RETURN NVL(V_AVG,0);
END;
/

-- Total Published Papers

CREATE OR REPLACE FUNCTION GET_TOTAL_PUBLICATIONS
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM PAPERS
    WHERE STATUS='PUBLISHED';

    RETURN V_TOTAL;
END;
/

-- Supervisor Workload

CREATE OR REPLACE FUNCTION GET_SUPERVISOR_WORKLOAD(
    P_SUPERVISOR_ID NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM THESIS_SUPERVISIONS
    WHERE SUPERVISOR_ID=P_SUPERVISOR_ID;

    RETURN V_TOTAL;
END;
/